"""Crew workflow data models."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional


class RequestType(str, Enum):
    """Supported request types for the workflow."""

    NEW_REQUIREMENT = "new_requirement"
    BUG = "bug"
    OPTIMIZATION = "optimization"


class TaskStatus(str, Enum):
    """Simple task status values."""

    TODO = "todo"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    DONE = "done"


@dataclass
class CrewRequest:
    """User request coming into the workflow."""

    request_type: RequestType
    title: str
    details: str
    confirmed: bool = False
    metadata: Dict[str, str] = field(default_factory=dict)


@dataclass
class TestCase:
    """Test case generated by the workflow."""

    case_id: str
    title: str
    steps: List[str]
    expected: List[str]
    priority: str = "P1"
    case_type: str = "functional"
    scope: str = "blackbox"


@dataclass
class Task:
    """Task tracked in docs/tasks.md."""

    task_id: str
    title: str
    description: str
    assignee: str
    status: TaskStatus = TaskStatus.TODO
    created_at: str = field(default_factory=lambda: datetime.utcnow().strftime("%Y-%m-%d"))
    updated_at: str = field(default_factory=lambda: datetime.utcnow().strftime("%Y-%m-%d"))
    metadata: Dict[str, str] = field(default_factory=dict)


@dataclass
class ReviewResult:
    """Review outcome for a task."""

    approved: bool
    notes: Optional[str] = None


@dataclass
class WorkflowResult:
    """Final workflow status."""

    success: bool
    message: str
    tasks: List[Task] = field(default_factory=list)
    tests_added: List[TestCase] = field(default_factory=list)
