#!/usr/bin/env python3
"""
Generate src/_build_info.py with the current git commit hash.

This is intended for build pipelines (PyInstaller / wheel) so `--version` can
still show a commit hash even when `.git` is not shipped with the artifact.
"""

from __future__ import annotations

import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path


def _run(cmd: list[str], cwd: Path) -> str:
    cp = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, check=False)
    if cp.returncode != 0:
        return ""
    return cp.stdout.strip()


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    out_path = repo_root / "src" / "_build_info.py"

    # Prefer GitHub-provided SHA when available.
    sha_full = os.environ.get("GITHUB_SHA", "").strip()
    if not sha_full:
        sha_full = _run(["git", "rev-parse", "HEAD"], cwd=repo_root)

    sha_short = ""
    if sha_full:
        sha_short = sha_full[:7]
    else:
        sha_short = _run(["git", "rev-parse", "--short", "HEAD"], cwd=repo_root)
        sha_full = sha_short

    build_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    # Release channel marker for display/version semantics (stable|beta).
    # Default to stable unless explicitly set by CI/pipeline.
    release_channel = os.environ.get("PROJMAN_RELEASE_CHANNEL", "").strip().lower() or "stable"
    if release_channel not in {"stable", "beta"}:
        release_channel = "stable"

    content = "\n".join(
        [
            "# Auto-generated by scripts/write_build_info.py. Do not edit.",
            f'GIT_SHA = "{sha_short}"',
            f'GIT_SHA_FULL = "{sha_full}"',
            f'BUILD_TIME_UTC = "{build_time}"',
            f'RELEASE_CHANNEL = "{release_channel}"',
            "",
        ]
    )
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path} (GIT_SHA={sha_short} RELEASE_CHANNEL={release_channel})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
