#!/usr/bin/env python3
"""
Generate src/_build_info.py with the current git commit hash.

This is intended for build pipelines (PyInstaller / wheel) so `--version` can
still show a commit hash even when `.git` is not shipped with the artifact.
"""

from __future__ import annotations

import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path


def _run(cmd: list[str], cwd: Path) -> str:
    cp = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, check=False)
    if cp.returncode != 0:
        return ""
    return cp.stdout.strip()


def _has_stable_tag(repo_root: Path) -> bool:
    tags = _run(["git", "tag", "--points-at", "HEAD"], cwd=repo_root)
    if not tags:
        return False
    return any(tag.strip().startswith("v") for tag in tags.splitlines())


def _resolve_release_channel(repo_root: Path) -> str:
    explicit = os.environ.get("PROJMAN_RELEASE_CHANNEL", "").strip().lower()
    if explicit in {"stable", "beta"}:
        return explicit

    github_ref = os.environ.get("GITHUB_REF", "").strip()
    github_ref_type = os.environ.get("GITHUB_REF_TYPE", "").strip().lower()
    if github_ref_type == "tag" and github_ref.startswith("refs/tags/v"):
        return "stable"

    if _has_stable_tag(repo_root):
        return "stable"

    # Untagged repository builds are prerelease/dev builds by default.
    return "beta"


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    out_path = repo_root / "src" / "_build_info.py"

    # Prefer GitHub-provided SHA when available.
    sha_full = os.environ.get("GITHUB_SHA", "").strip()
    if not sha_full:
        sha_full = _run(["git", "rev-parse", "HEAD"], cwd=repo_root)

    sha_short = ""
    if sha_full:
        sha_short = sha_full[:7]
    else:
        sha_short = _run(["git", "rev-parse", "--short", "HEAD"], cwd=repo_root)
        sha_full = sha_short

    build_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    # Release channel marker for display/version semantics (stable|beta).
    # Stable is reserved for tagged release builds or explicit CI overrides.
    release_channel = _resolve_release_channel(repo_root)

    content = "\n".join(
        [
            "# Auto-generated by scripts/write_build_info.py. Do not edit.",
            f'GIT_SHA = "{sha_short}"',
            f'GIT_SHA_FULL = "{sha_full}"',
            f'BUILD_TIME_UTC = "{build_time}"',
            f'RELEASE_CHANNEL = "{release_channel}"',
            "",
        ]
    )
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path} (GIT_SHA={sha_short} RELEASE_CHANNEL={release_channel})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
